### ISSUE TITLE
Assets getting rejected by browser as not having correct content-type

### ISSUE THREAD

**Issue by yorch** [SoftwareBrothers/adminjs-fastify#1]
When I try to load AdminJS on the Chrome (also tested with Firefox), getting errors on the JS assets:

`Refused to execute script from 'http://localhost:3000/admin/frontend/assets/global.bundle.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.`

![image](https://user-images.githubusercontent.com/60499/150375339-796d58cf-f501-47fa-8163-0a5cce817ee4.png)

**Comment by dziraf** [comment]
Fixed in https://github.com/SoftwareBrothers/adminjs-fastify/pull/2

**Comment by yorch** [comment]
thanks!
